name: Run fuzzy search tests

on:
  push:
    paths:
      - 'FuseNET/**'
      - '.github/workflows/test.yml'
      - 'FuseNET.Test/**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x
      - name: Test
        run: dotnet test FuseNET.Test
